In [1]:
import numpy as np

In [8]:
#array
x=np.array([1,2,3,4])
print(x)
print(type(x))

[1 2 3 4]
<class 'numpy.ndarray'>


In [7]:
y=[1,2,3,4]
print(y)
print(type(y))

[1, 2, 3, 4]
<class 'list'>


In [15]:
%timeit [j**4 for j in range(1,9)]

1.78 µs ± 81.4 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [19]:
%timeit np.arange(1,9)**4

4.79 µs ± 145 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


*****************Array*****

In [20]:
x=[1,2,3,4]
y=np.array(x)
y

array([1, 2, 3, 4])

In [30]:
y=np.array([1, 2, 3, 4])
print(y)
print(type(y))


[1 2 3 4]
<class 'numpy.ndarray'>
1


In [27]:
l=[]
for i in range(1,5):
 int_1=int(input("enter"))
 l.append(int_1)
print(np.array(l))

enter 10
enter 20
enter 30
enter 40


[10 20 30 40]


In [31]:
print(y.ndim)#dimension of array

1


In [34]:
ar2=np.array([[1,2,3,4],[2,3,4,5]])
print(ar2)
print(ar2.ndim)

[[1 2 3 4]
 [2 3 4 5]]
2


In [35]:
ar1=np.array([[1,2,3],[2,3,4,5]])#same no of parameter should be used
ar1

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.

In [36]:
ar3=np.array([[[1,2,3,4],[1,4,3,2],[1,2,3,4]]])
print(ar3)
print(ar3.ndim)

[[[1 2 3 4]
  [1 4 3 2]
  [1 2 3 4]]]
3


In [40]:
arn=np.array([1,2,3,4],ndmin=10)#no of dimension array can be fixed
print(arn)
print(arn.ndim)

[[[[[[[[[[1 2 3 4]]]]]]]]]]
10


********using functions**********->zeroes,ones,range,diagonal with 1's, linspaced

In [41]:
#zeroes
ar_zero=np.zeros(4)
ar_zero

array([0., 0., 0., 0.])

In [43]:
ar_zero=np.zeros([4,3])
ar_zero

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [44]:
#ones
ar_one=np.ones(4)
ar_one

array([1., 1., 1., 1.])

In [45]:
ar_one=np.ones([4,6])
ar_one

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [47]:
#empty
ar_em=np.empty(4)#pevious data will be come in empty element
ar_em

array([1., 1., 1., 1.])

In [48]:
#range
ar_rn=np.arange(4)#same as range element
ar_rn

array([0, 1, 2, 3])

In [49]:
#diagonal with 1's
ar_fin=np.eye(3)#3x3 matrix is created and diagonal contain 1 's
ar_fin

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [51]:
ar_fin=np.eye(3,5)#3x5 matrix is created and diagonal contain 1 's
ar_fin

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.]])

In [54]:
### line spaced
ar_lin=np.linspace(1,10,num=5)# first two elements are range and third elements are no of elements
ar_lin

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

************Array with random number*******->rand(),randn(),ranf(),randint()

In [56]:
#rand()->between 0 and 1,values changes for every run
var=np.random.rand(4)
var

array([0.2724512 , 0.43059014, 0.43182587, 0.29894993])

In [57]:
var=np.random.rand(4,3)
var

array([[0.17476131, 0.21106639, 0.67755428],
       [0.7287021 , 0.97988195, 0.09764048],
       [0.28503593, 0.18804942, 0.0673535 ],
       [0.29048887, 0.77947913, 0.40150485]])

In [59]:
#randn->close to 0, +ve and-ve
var=np.random.randn(4)
var

array([-1.79570438,  0.06516877, -0.45190968,  2.06930746])

In [60]:
var=np.random.randn(4,3)
var

array([[ 0.6105337 , -0.50731193, -0.42439101],
       [-0.69194825,  1.65118159, -0.05205514],
       [-0.46829369, -0.97901122,  0.58772221],
       [ 0.67600312, -0.93389754,  0.51652937]])

In [62]:
#ranf->specified shape from 0 to 1
var=np.random.ranf(4)
var

array([0.59162689, 0.3463364 , 0.14998719, 0.87819421])

In [63]:
var=np.random.ranf([4,4])
var

array([[0.82422118, 0.79650743, 0.52912401, 0.53182742],
       [0.11827861, 0.23203662, 0.1500639 , 0.4079674 ],
       [0.16404356, 0.13937751, 0.24862239, 0.64436869],
       [0.65300295, 0.50630939, 0.72547264, 0.97506061]])

In [67]:
#randint
var=np.random.randint(1,30,7)#(min=1,max=30,total_values=7)
var

array([14, 16,  9, 28,  3, 29, 17])

***********datatype*************

In [68]:
ar2=np.array([[1,2,3,4,2,3,4,5]])
print(ar2.dtype)

int32


In [69]:
ar2=np.array([[1.0,2.7,3.7,4.6,2,3,4,5]])
print(ar2.dtype)

float64


In [70]:
ar2=np.array(["v","a","r","s","h","a"])
print(ar2.dtype)

<U1


In [73]:
ar2=np.array([1,2,3,4,2,3,4,5],dtype=np.float64)
print(ar2.dtype)
ar2

float64


array([1., 2., 3., 4., 2., 3., 4., 5.])

In [75]:
ar2=np.array([1,2,3,4,2,3,4,5],dtype="f")
print(ar2.dtype)
ar2

float32


array([1., 2., 3., 4., 2., 3., 4., 5.], dtype=float32)

In [76]:
ar2=np.array([[1,2,3,4,2,3,4,5]])
new=np.float32(ar2)
print(ar2)
print(ar2.dtype)
print(new)
print(new.dtype)

[[1 2 3 4 2 3 4 5]]
int32
[[1. 2. 3. 4. 2. 3. 4. 5.]]
float32


In [80]:
ar2=np.array([[1,2,3,4,2,3,4,5]])
new=ar2.astype(float)
print(ar2)
print(ar2.dtype)
print(new)
print(new.dtype)

[[1 2 3 4 2 3 4 5]]
int32
[[1. 2. 3. 4. 2. 3. 4. 5.]]
float64


*****************Arithmetic operation******************

In [81]:
ar2=np.array([1,2,3,4])
var=np.array([6,2,5,4])
varadd=var+3
varadd

array([9, 5, 8, 7])

In [82]:
ar2=np.array([1,2,3,4])
var=np.array([6,2,5,4])
varadd=var+ar2
varadd

array([7, 4, 8, 8])

In [83]:
var=np.array([6,2,5,4])
varsub=var-3
varsub

array([ 3, -1,  2,  1])

In [84]:
var=np.array([6,2,5,4])
varmul=var*3
varmul

array([18,  6, 15, 12])

In [85]:
var=np.array([6,2,5,4])
vard=var/3
vard

array([2.        , 0.66666667, 1.66666667, 1.33333333])

In [86]:
var=np.array([6,2,5,4])
varmod=var%3
varmod

array([0, 2, 2, 1], dtype=int32)

In [87]:
ar2=np.array([1,2,3,4])
var=np.array([6,2,5,4])
print(np.add(ar2,var))

[7 4 8 8]


In [89]:
ar2=np.array([1,2,3,4])
var=np.array([6,2,5,4])
print(np.subtract(ar2,var))

[-5  0 -2  0]


In [90]:
ar2=np.array([1,2,3,4])
var=np.array([6,2,5,4])
print(np.add(ar2,3))

[4 5 6 7]


In [91]:
ar2=np.array([1,2,3,4])
var=np.array([6,2,5,4])
print(np.multiply(ar2,var))

[ 6  4 15 16]


In [92]:
ar2=np.array([1,2,3,4])
var=np.array([6,2,5,4])
print(np.divide(ar2,var))

[0.16666667 1.         0.6        1.        ]


In [93]:
ar2=np.array([1,2,3,4])
var=np.array([6,2,5,4])
print(np.mod(ar2,var))

[1 0 3 0]


In [94]:
ar2=np.array([1,2,3,4])
var=np.array([6,2,5,4])
print(np.power(ar2,var))

[  1   4 243 256]


In [95]:
ar2=np.array([1,2,3,4])
var=np.array([6,2,5,4])
print(np.reciprocal(ar2,var))

[1 0 0 0]


In [96]:
ar2=np.array([1,2,3,4])
var=np.array([6,2,5,4])
print(np.reciprocal(ar2))

[1 0 0 0]


In [98]:
#2d array
ar2=np.array([[1,2,3,4],[5,7,8,9]])
var=np.array([6,2,5,4])
print(np.add(ar2,5))

[[ 6  7  8  9]
 [10 12 13 14]]


In [102]:
ar2=np.array([[1,2,3,4],[5,7,8,9]])
var=np.array([[6,2,5,4],[1,2,3,4]])
print(np.multiply(ar2,var))

[[ 6  4 15 16]
 [ 5 14 24 36]]


In [103]:
var=np.array([6,2,5,4])
print(np.min(var))

2


In [104]:
var=np.array([6,2,5,4])
print(np.max(var))

6


In [113]:
var=np.array([6,2,5,4])
print("position of min",np.argmin(var))#position
print("position of max",np.argmax(var))
print("sqrt",np.sqrt(var))

position of min 1
position of max 0
sqrt [2.44948974 1.41421356 2.23606798 2.        ]


In [109]:
var=np.array([[6,2,5,4],[1,2,3,4]])
print(np.min(var))


1


In [111]:
var=np.array([[6,2,5,4],[1,2,3,4]])
print(np.min(var,axis=0))



[1 2 3 4]


In [112]:
var=np.array([[6,2,5,4],[1,2,3,4]])
print(np.min(var,axis=1))

[2 1]


In [119]:
var=np.array([6,2,5,4])
print("sin",np.sin(var))
print("cos",np.cos(var))


sin [-0.2794155   0.90929743 -0.95892427 -0.7568025 ]
cos [ 0.96017029 -0.41614684  0.28366219 -0.65364362]


In [121]:
#cumsum
var=np.array([6,2,5,4])
print(np.cumsum(var))

[ 6  8 13 17]


***************shapeand reshape**************

In [2]:
#shape
var=np.array([[1,2],[1,2]])
print(var)

[[1 2]
 [1 2]]


In [3]:
var.shape


(2, 2)

In [4]:
var=np.array([[1,2,5],[1,2,8]])
var.shape


(2, 3)

In [8]:
var1=np.array([1,2,3,4],ndmin=4)
var1

array([[[[1, 2, 3, 4]]]])

In [9]:
var1.shape #how many square braces are there are first represented

(1, 1, 1, 4)

In [14]:
#reshape
var1=np.array([1,2,3,4,5,6])
print(var1.ndim)
x=var1.reshape(3,2)
print(x.ndim)
x

1
2


array([[1, 2],
       [3, 4],
       [5, 6]])

In [17]:
#1 dimension to 3 dimension
var1=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(var1.ndim)
x=var1.reshape(2,3,2)
print(x.ndim)
x

1
3


array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]]])

In [18]:
#3 dim to 1 dim
one=x.reshape(-1)
one
print(one.ndim)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

*******************************broadcasting*******************************

In [20]:
var=np.array([ 1,  2,  3,  4,  5,  6])
var1=np.array([7,  8,  9, 10, 11, 12])
var+var1


array([ 8, 10, 12, 14, 16, 18])

In [23]:
var=np.array([ 1,  2,  3])
var1=np.array([[7], [ 8], [ 9]])
var+var1

array([[ 8,  9, 10],
       [ 9, 10, 11],
       [10, 11, 12]])

In [28]:
var=np.array([[ 1], [ 2]])
var1=np.array([[7,5,6], [ 8,7,6]])
var+var1


array([[ 8,  6,  7],
       [10,  9,  8]])

In [29]:
print((var+var1).ndim)

2


In [ ]:
************************Indexing and Slicing in  numpy***********************

In [30]:
#indexing
var=np.array([ 1,  2,  3])
                #0  1   2
                 #-3 -2 -1
var[1]

2

In [31]:
var[-3]

1

In [35]:
var=np.array([[1,2,5],[1,2,8]])
print(var[0,2])
var[0][2]

5


5

In [36]:
var=np.array([[[1,2,5],[1,2,8]]])
var.ndim

3

In [37]:
var[0][1][2]

8

In [38]:
var[0,1,2]

8

In [41]:
print(var[0,1])
var[0]

[1 2 8]


array([[1, 2, 5],
       [1, 2, 8]])

In [45]:
#slicing
var=np.array([ 1,  2,  3,  4,  5,  6])
var[1:5:1]#start at index 1 and stop at index 4 and only one character at a time

array([2, 3, 4, 5])

In [47]:
var[1:]#start at index 1 and stop at indexend and only one character at a time

array([2, 3, 4, 5, 6])

In [49]:
var[:5]#start at index 0 and stop at index 5 and only one character at a time

array([1, 2, 3, 4, 5])

In [50]:
   var[::]#start at index 0 and stop at index end and only one character at a time

array([1, 2, 3, 4, 5, 6])

In [51]:
var[1:5:2]#start at index 1 and stop at index 4 and only 2 character at a time

array([2, 4])

In [52]:
var=np.array([[1,2,5],[1,2,8]])
var[1,1:]

array([2, 8])

In [53]:
var[1:]

array([[1, 2, 8]])

*************************iterating numpy array*************************

In [55]:
var=np.array([ 1,  2,  3,  4,  5,  6])
for i in var:
   print( i)
   

1
2
3
4
5
6


In [56]:
var=np.array([[1,2,5],[1,2,8]])
for i in var:
   print( i)

[1 2 5]
[1 2 8]


In [58]:
for i in var:
    for j in var:
        print( j)
        
   

[1 2 5]
[1 2 8]
[1 2 5]
[1 2 8]


In [59]:
for i in var:
    for j in i:
        print( j)

1
2
5
1
2
8


In [60]:
var=np.array([[[1,2,5],[1,2,8]]])
for i in var:
    for j in i:
        for n in j:
             print( n)
            
       

1
2
5
1
2
8


In [61]:
for i in np.nditer(var):#without using more for loops
    print(i)

1
2
5
1
2
8


In [67]:
for i in np.nditer(var,flags=["buffered"],op_dtypes=['S']):#conversion of datatype
    print(i)

b'1'
b'2'
b'5'
b'1'
b'2'
b'8'


In [68]:
for i,e in np.ndenumerate(var):#conversion of datatype
    print(i,e)

(0, 0, 0) 1
(0, 0, 1) 2
(0, 0, 2) 5
(0, 1, 0) 1
(0, 1, 1) 2
(0, 1, 2) 8


************************Copy and view****************

In [69]:
var=np.array([ 1,  2,  3,  4,  5,  6])
co=var.copy()#used to copy own data a new locatio is used
co

array([1, 2, 3, 4, 5, 6])

In [71]:
x=np.array([ 1,  2,  3,  4,  5,  6])
vi=x.view()#does nt own data any change affect array
vi

array([1, 2, 3, 4, 5, 6])

In [73]:
var=np.array([ 1,  2,  3,  4,  5,  6])
var[1]=24
co=var.copy()#used to copy own data a new locatio is used
co

array([ 1, 24,  3,  4,  5,  6])

In [74]:
x=np.array([ 1,  2,  3,  4,  5,  6])
x[1]=34
vi=x.view()#does nt own data any change affect array
vi

array([ 1, 34,  3,  4,  5,  6])

******************************join and split*********************

In [76]:
var=np.array([ 1,  2,  3,  4,  5,  6])
x=np.array([ 1,  2, 7,8, 5,  6])
ar=np.concatenate((var,x))
ar

array([1, 2, 3, 4, 5, 6, 1, 2, 7, 8, 5, 6])

In [78]:
var=np.array([[1,2,5],[1,2,8]])
var1=np.array([[1,2,4],[3,5,8]])
ar=np.concatenate((var,var1))
ar

array([[1, 2, 5],
       [1, 2, 8],
       [1, 2, 4],
       [3, 5, 8]])

In [79]:
ar=np.concatenate((var1,var))
ar

array([[1, 2, 4],
       [3, 5, 8],
       [1, 2, 5],
       [1, 2, 8]])

In [81]:
var=np.array([[1,2,5],[1,2,8]])
var1=np.array([[1,2,4],[3,5,8]])

ar=np.concatenate((var,var1),axis=0)
print("row",ar)
vvar=np.concatenate((var,var1),axis=1)
print("col",vvar)

row [[1 2 5]
 [1 2 8]
 [1 2 4]
 [3 5 8]]
col [[1 2 5 1 2 4]
 [1 2 8 3 5 8]]


In [82]:
var=np.array([[1,2,5],[1,2,8]])
var1=np.array([[1,2,4],[3,5,8]])
ar=np.stack((var,var1))
ar

array([[[1, 2, 5],
        [1, 2, 8]],

       [[1, 2, 4],
        [3, 5, 8]]])

In [85]:
var=np.array([ 1,  2,  3,  4,  5,  6])
var1=np.array([ 1,  2, 7,8, 5,  6])

ar=np.stack((var,var1),axis=0)
print("row",ar)
ar=np.stack((var,var1),axis=1)
print("col",ar)

row [[1 2 3 4 5 6]
 [1 2 7 8 5 6]]
col [[1 1]
 [2 2]
 [3 7]
 [4 8]
 [5 5]
 [6 6]]


In [88]:
var=np.array([ 1,  2,  3,  4,  5,  6])
var1=np.array([ 1,  2, 7,8, 5,  6])

ar=np.vstack((var,var1))
ar

array([[1, 2, 3, 4, 5, 6],
       [1, 2, 7, 8, 5, 6]])

In [89]:
ar=np.hstack((var,var1))
ar

array([1, 2, 3, 4, 5, 6, 1, 2, 7, 8, 5, 6])

In [90]:
ar=np.dstack((var,var1))
ar

array([[[1, 1],
        [2, 2],
        [3, 7],
        [4, 8],
        [5, 5],
        [6, 6]]])

In [91]:
#split
var=np.array([ 1,  2,  3,  4,  5,  6])
ar=np.array_split(var,3)
ar

[array([1, 2]), array([3, 4]), array([5, 6])]

In [92]:
print(type(ar))

<class 'list'>


*******************search*************************

In [89]:
ar=np.array([ [1,3,5,7],[10,11,16,20],[23,30,34,60]])
#              0   1   2   3   4   5 6 7 8
x=np.where(ar==13)
x

(array([], dtype=int64), array([], dtype=int64))

In [5]:
ar=np.array([ar=np.array([ 1,  2,  3,  4,  5,  6,1,3,4])
#              0   1   2   3   4   5 6 7 8
x=np.where(ar==1)
x)
#              0   1   2   3   4   5 6 7 8
x=np.where(ar==1)
x

(array([1, 3, 5, 8], dtype=int64),)

*********search sorted array**********

In [8]:
ar=np.array([ 1,  2,    4,  5,  6])
#              0   1   2   3   4  
x=np.searchsorted(ar,3)
x

2

In [9]:
ar=np.array([ 1,  2,    4,  5,  6])
#              0   1   2   3   4  
x=np.searchsorted(ar,3,side="right")
x

2

In [11]:
ar=np.array([ 1,  2,    4,  5,  6])
#              0   1   2   3   4  
x=np.searchsorted(ar,[3,4,7],side="right")
x

array([2, 3, 5], dtype=int64)

***************sort***********

In [12]:
ar=np.array([ 1,  2, 12,22, 3, 15, 4,  5,  6])#alphabet possible
np.sort(ar)

array([ 1,  2,  3,  4,  5,  6, 12, 15, 22])

In [14]:
ar=np.array(["varsha","hima","sri","satya"])
np.sort(ar)

array(['hima', 'satya', 'sri', 'varsha'], dtype='<U6')

In [16]:
var=np.array([[12,2,5],[1,27,8]])
np.sort(var)

array([[ 2,  5, 12],
       [ 1,  8, 27]])

****************Filter*****************

In [21]:
#new array we will get
ar=np.array([ 1,  2, 12,22])
f=[True,False,True,False]
new_a=ar[f]
print(type(new_a))
new_a

<class 'numpy.ndarray'>


array([ 1, 12])

In [ ]:
**************shuffle\unique\resize\flatten\ravel***************

In [24]:

#shuffle
ar=np.array([ 1,  2, 12,22])
np.random.shuffle(ar)#after every run value changes
ar

array([12,  2, 22,  1])

In [28]:
#unique
ar=np.array([ 1,  2, 1,2,2,2,5,8])
x=np.unique(ar,return_index=True)
x

(array([1, 2, 5, 8]), array([0, 1, 6, 7], dtype=int64))

In [30]:
x=np.unique(ar,return_index=True,return_counts=True)
x

(array([1, 2, 5, 8]),
 array([0, 1, 6, 7], dtype=int64),
 array([2, 4, 1, 1], dtype=int64))

In [35]:
#resize
ar=np.array([ 1,  2, 1,12,22,23,5,8])
y=np.resize(ar,(3,3))
y


array([[ 1,  2,  1],
       [12, 22, 23],
       [ 5,  8,  1]])

In [36]:
y.flatten()#bt default c

array([ 1,  2,  1, 12, 22, 23,  5,  8,  1])

In [39]:
y.flatten(order="A")

array([ 1,  2,  1, 12, 22, 23,  5,  8,  1])

In [38]:
np.ravel(y)

array([ 1,  2,  1, 12, 22, 23,  5,  8,  1])

In [40]:
np.ravel(y,order="A")

array([ 1,  2,  1, 12, 22, 23,  5,  8,  1])

In [ ]:
********************Insert\Delete*********************

In [42]:
var=np.array([ 1,  2,  1, 12, 22, 23,  5,  8,  1])
var

array([ 1,  2,  1, 12, 22, 23,  5,  8,  1])

In [44]:
np.insert(var,2,45)#array name,position ,value

array([ 1,  2, 45,  1, 12, 22, 23,  5,  8,  1])

In [47]:
np.insert(var,[2,5],45)

array([ 1,  2,  4,  1, 12, 22,  4, 23,  5,  8,  1])

In [48]:
np.insert(var,[2,5],4.5)

array([ 1,  2,  4,  1, 12, 22,  4, 23,  5,  8,  1])

In [51]:
var4=np.array([[ 1,  2,  1],
       [12, 22, 23],
       [ 5,  8,  1]])
np.insert(var4,[2,5],45)

array([ 1,  2, 45,  1, 12, 22, 45, 23,  5,  8,  1])

In [58]:
x=np.append(var4,6.5)#last pos
x

array([ 1. ,  2. ,  1. , 12. , 22. , 23. ,  5. ,  8. ,  1. ,  6.5])

In [61]:
x=np.append(var4,[[1,2]],axis=0)#last pos
x

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 3 and the array at index 1 has size 2

In [64]:
var4=np.array([[ 1,  2,  1],
       [12, 22, 23],
       [ 5,  8,  1]])
d=np.delete(var4,2)
d

array([ 1,  2, 12, 22, 23,  5,  8,  1])

****************Matrix********************

In [66]:
var=np.matrix([[ 1,  2,  1],
       [12, 22, 23],
       [ 5,  8,  1]])
var

matrix([[ 1,  2,  1],
        [12, 22, 23],
        [ 5,  8,  1]])

In [67]:
var=np.array([[ 1,  2,  1],
       [12, 22, 23],
       [ 5,  8,  1]])
var

array([[ 1,  2,  1],
       [12, 22, 23],
       [ 5,  8,  1]])

In [71]:
var=np.matrix([[ 1,  2,  1],
       [12, 22, 23],
       [ 5,  8,  1]])
var1=np.matrix([[ 1,  2,  31],
       [12, 2, 2],
       [ 5,  8,  17]])
var+var1

matrix([[ 2,  4, 32],
        [24, 24, 25],
        [10, 16, 18]])

In [72]:
var-var1

matrix([[  0,   0, -30],
        [  0,  20,  21],
        [  0,   0, -16]])

In [73]:
var*var1

matrix([[ 30,  14,  52],
        [391, 252, 807],
        [106,  34, 188]])

**************matrix func->transpose,swapaxes,inverse,power,determinate***********

In [75]:
b=np.matrix([[ 30,  14,  52],
        [391, 252, 807],
        [106,  34, 188]])
b

matrix([[ 30,  14,  52],
        [391, 252, 807],
        [106,  34, 188]])

In [76]:
np.transpose(b)

matrix([[ 30, 391, 106],
        [ 14, 252,  34],
        [ 52, 807, 188]])

In [77]:
b.T

matrix([[ 30, 391, 106],
        [ 14, 252,  34],
        [ 52, 807, 188]])

In [79]:
#swapaxss
np.swapaxes(b,0,1)

matrix([[ 30, 391, 106],
        [ 14, 252,  34],
        [ 52, 807, 188]])

In [80]:
#inverse
np.linalg.inv(b)

matrix([[ 0.28945993, -0.01254355, -0.02621951],
        [ 0.17470964,  0.0018583 , -0.05630081],
        [-0.19480256,  0.00673635,  0.03028455]])

In [85]:

var=np.matrix([[ 1,  2,  1],
       [12, 22, 23],
       [ 5,  8,  1]])
np.linalg.matrix_power(var,2)

matrix([[ 30,  54,  48],
        [391, 692, 541],
        [106, 194, 190]])

In [86]:
np.linalg.matrix_power(var,0)

matrix([[1, 0, 0],
        [0, 1, 0],
        [0, 0, 1]])

In [87]:
np.linalg.matrix_power(var,-2)#inverse

matrix([[ 29.47333333,  -1.05333333,  -4.44666667],
        [-18.82666667,   0.68      ,   2.82      ],
        [  2.78      ,  -0.10666667,  -0.39333333]])

In [88]:
#determinant
np.linalg.det(b)

68880.00000000001